<a href="https://colab.research.google.com/github/Eliminator746/kirat-Backend/blob/main/numpy2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY - Chai aur Code

In [ ]:
import numpy as np

[1 2 3 4 5]
[0 1 2 3 4]


### **Creating Array from List**

In [ ]:
arr_1d= np.array([1,2,3,4,5])
print('1D Array : ', arr_1d)

arr_2d= np.array([[1,2,3],[4,5,6]])
print('2D Array : ', arr_2d)

1D Array :  [1 2 3 4 5]
2D Array :  [[1 2 3]
 [4 5 6]]


## **List Vs Numpy Array**

In [ ]:
py_list=[1,2,3]
print("Python list Multiplication : ", py_list*2)

np_array=np.array([1,2,3])
print("Numpy Array Multiplication : ", np_array*2)

Python list Multiplication :  [1, 2, 3, 1, 2, 3]
Numpy Array Multiplication :  [2 4 6]


**Numpy array is faster than Python List**

In [ ]:
import time
start= time.time()
# py_list = [i*2 for i in range(10000000)]
py_list= list(range(10000000)) * 2
print('List opertaion time: ', time.time()- start)

start= time.time()
# np_array= [i*2 for i in range(10000000)]
np_array= np.arange(10000000)*2
print('Numpy Array opertaion time: ', time.time()- start)

List opertaion time:  1.3932561874389648
Numpy Array opertaion time:  0.018100738525390625


## **Creating array from scratch**

In [ ]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

# 1st random is class, 2nd random is method. Random runs b/w 0-1

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [1. 1.]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.74346848 0.12988906 0.24355836]
 [0.20493201 0.67652999 0.88765161]]
sequnce array: 
 [ 0  2  4  6  8 10]


In [ ]:
vector = np.array([1,2,3])
matrices = np.array([[1,2,3],[4,5,6]])
tensor= np.array([ [[1,2],[3,4]], [[5,6],[7,8]] ])

print("Vector: ", vector)
print("Matrix: ", matrices)
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape ", arr.shape)     #(2,3)
print("Dimension ", arr.ndim)  #2 : horizontal + vertical i.e row + col
print("Size ", arr.size)       #6
print("DType ", arr.dtype)     #int64

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


## **Array Reshaping**

In [ ]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## **Numpy Array operations**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


## **Sorting**

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


In numpy we can write expressions inside [], bracket

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.shape)
print(a[a<7])

c = a[(a > 2) & (a < 11)]     # satisfy two conditions using the & and | operators
print(c)

mask = a > 5
print("Numbers greater than 5 : ", a[mask])

(3, 4)
[1 2 3 4 5 6]
[ 3  4  5  6  7  8  9 10]
Numbers greater than 5 :  [ 6  7  8  9 10 11 12]


## **Fancy indexing vs np.where()**

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

indices=[0,2,4]
print(numbers[indices])       # We are storing multiple indices and getting all the o/ps

where_result = np.where(numbers > 5)
print(where_result)           # Gives indices
print(numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)
# Think this as -> number > 5 ? true : false, will run on individual

condition_array = np.where(numbers > 5, numbers*4,  numbers)
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']
[ 1  2  3  4  5 24 28 32 36 40]


Operation	View or Copy?

Basic Indexing (x[1])	✅ View


Slicing (x[:, 1:])	✅ View


Fancy Indexing (x[[1, 2]])	❌ Copy


Explicit Copy (x.copy())	❌ Copy

In [ ]:
import numpy as np

# Create a 1D array
x = np.arange(9)
print(x)  # Output: [0 1 2 3 4 5 6 7 8]

# Reshape it into a 3x3 matrix
y = x.reshape(3, 3)
print(y)
# Output:
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]

# Check the base of the reshaped array
print(y.base)  # Output: [0 1 2 3 4 5 6 7 8] (points to the original array `x`)
print(np.shares_memory(x, y))  # True (view), False (copy)

# Using advanced indexing to create a new array
z = y[[2, 1]]
print(z)
# Output:
# [[6 7 8]
#  [3 4 5]]

# Check if `z` is a view or a copy
print(z.base is None)  # Output: True (because advanced indexing creates a copy)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
True
[[6 7 8]
 [3 4 5]]
True


## **View or Copy ?**

## Check View and it does shares memory
## **1. y.base**
### If points to the original array `x` then it is view else not
#### print(y.base)  
Output: [0 1 2 3 4 5 6 7 8] (points to the original array x)

## **2. np.shares_memory(x, y)**

### True means view, False means copy
#### print(np.shares_memory(x, y))  # Output: True (because `y` is a view of `x`)


In [ ]:
import numpy as np
x = np.arange(9)
print('x : ', x)
y = x.reshape(3, 3)
print('\ny : ', y)
y.base  # .reshape() creates a view
z = y[[2, 1]]
print('\nz : ', z)
# advanced indexing creates a copy
print('\nbase : ',z.base)  # NONE : means copy
print('shares_memory : ',np.shares_memory(y, z))  # False (copy)

x :  [0 1 2 3 4 5 6 7 8]

y :  [[0 1 2]
 [3 4 5]
 [6 7 8]]

z :  [[6 7 8]
 [3 4 5]]

base :  None
shares_memory :  False


In [ ]:
x = np.arange(6).reshape(2, 3)  # 2D array
y = x.T.reshape(3, 2)  # Transpose first, then reshape

y[0, 0] = 999  # Modify y

print(x)  # x remains unchanged! , .reshape() creates a copy
print(y)


[[999   1   2]
 [  3   4   5]]
[[999   3]
 [  1   4]
 [  2   5]]


## **Adding and removing data**

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
combined = np.concatenate((x, y), axis=0) # axis=0 -> Concatenation along rows (i.e., adding more rows).
print(combined)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)
print("Compatibility shapes", a.shape == c.shape)

Compatibility shapes False
Compatibility shapes True


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))  # adds new row -> vstack : vertical stack
print(original)
print('\n',with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))  # adds new coln -> hstack : horizontal stack, hstack adds new coln
print("\nWith new column", with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

With new column [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2) # removes index at 2
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]


# PANDAS - Data Sets Manipulation

In [ ]:
import json
# from google.colab import files

# # This will prompt the file upload dialog
# uploaded = files.upload()


with open('house-price.json', 'r') as file:
     data = json.load(file)

for item in data:
  print(item)


## **Basics**

In [ ]:
import pandas as pd
df= pd.read_csv("panda_dataset/countries of the world.csv")
df

In [ ]:
df = pd.read_csv('panda_dataset/countries of the world.txt', sep='\t')
df

In [ ]:
# pd.read_csv("panda_dataset/countries of the world.csv")                 # Read CSV file
# pd.read_table('panda_dataset/countries of the world.txt').head()        # Read txt file
# pd.read_json('panda_dataset/json_sample.json')                          # Read JSON file
# pd.read_excel('panda_dataset/world_population_excel_workbook.xlsx')     # Read Excel file -> By default show 1st table of 1st sheet
pd.read_excel('panda_dataset/world_population_excel_workbook.xlsx', sheet_name='Sheet1')  # Mention which sheet to see


head() --> Display top 5 file


tail(10)

**To see all row**


pd.set-option('display.max.rows',235) : 234 rows * 4 colns

Object : -> means String

In Pandas, text/string columns are stored as object

In [ ]:
# df= pd.read_csv("panda_dataset/countries of the world.csv")
# df.to_excel("panda_dataset/countries of the world.xlsx", sheet_name="passengers", index=False)   # Change the file extension to .xlsx, File name written, it will be stored in that excel sheet

pd.read_excel("panda_dataset/countries of the world.xlsx")


In [ ]:
df= pd.read_excel('panda_dataset/world_population_excel_workbook.xlsx').head(2)
# pd.set_option('display.max.rows', 235)                                  # To See all the rows
# pd.set_option('display.max.columns', 40)                                # To See all the columns
# print(df)
df

Rank CCA3      Country Capital Continent  2022 Population  2020 Population  \
0    36  AFG  Afghanistan   Kabul      Asia         41128771         38972230   
1   138  ALB      Albania  Tirana    Europe          2842321          2866849   

   2015 Population  2010 Population  2000 Population  1990 Population  \
0         33753499         28189672         19542982         10694796   
1          2882481          2913399          3182021          3295066   

   1980 Population  1970 Population  Area (km²)  Density (per km²)  \
0         12486631         10752971       652230             63.0587   
1          2941651          2324731        28748             98.8702   

   Growth Rate  World Population Percentage  
0       1.0257                         0.52  
1       0.9957                         0.04

In [ ]:
# df.info()
df= pd.read_csv("panda_dataset/countries of the world.csv")
df['Country']

In [ ]:
import pandas as pd
df= pd.read_csv("sample_data/world_population.csv")

# df["Rank"].head()
two_colns= df[["Rank", "Country"]]
# To select multiple columns, use a list of column names within the selection brackets [].

two_colns
# df[df['Rank'] < 10]

Rank            Country
0      36        Afghanistan
1     138            Albania
2      34            Algeria
3     213     American Samoa
4     203            Andorra
..    ...                ...
229   226  Wallis and Futuna
230   172     Western Sahara
231    46              Yemen
232    63             Zambia
233    74           Zimbabwe

[234 rows x 2 columns]

In [ ]:
specific_countries=['Bangladesh','India']
df[df['Country'].isin(specific_countries)]    # IN operator in SQL, i.e OR
df[df['Country'].str.contains('United')]      # LIKE operator in SQL

# or_operator= df[(df['Country']=='Bangladesh') | (df['Country']=='India') ]
# or_operator.head()


# AND -> & , OR -> |

## **Working with Missing Data**

In [ ]:
data= pd.read_csv('sample_data/company1.csv')
# data
data.loc[data['salary'] <27000, ['Name','salary'] ]

Name   salary
1   rohit  25000.0
3  ayushi  20000.0
4     NaN  25000.0
6   rohit  25000.0

In [ ]:
# print(data.isnull())
# print(data.isnull().sum())
print(data.dropna())          # It'll delete any rows, whichever colns of that row is NaN


In [ ]:
notna_data= data[data['gender'].notna()]    # Will return rows whoes gender is not null i.e not NaN
notna_data.head()
# notna_data.shape

EEID    Name gender   salary
0  EMP01  ayushi      F      NaN
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
4  EMP05     NaN      M  25000.0
5  EMP06   rohit      M      NaN

In [ ]:
import numpy as np
# print(data.replace(np.nan, 'Missing'))
# print(data.replace(np.nan, 3000))

data['salary']= data['salary'].replace(np.nan, 3000)
data.head()

EEID      Name gender   salary
0  EMP01    ayushi      F   3000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0

In [ ]:
# Good practise to replace value is with that colns mean value

# data['salary'].mean() # 24400.0
data['salary']= data['salary'].replace(np.nan, data['salary'].mean())
data.head()

EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0

## **Working with Duplicate Values**

In [ ]:
import numpy as np
data= pd.read_csv('sample_data/company1.csv')

In [ ]:
# print(data['EEID'].duplicated())
print(data['EEID'].duplicated().sum())    # Gives total count of duplicates
# print(data.drop_duplicates(['EEID']))    # Drop duplicates


2


## **Filter based on Index**

In [ ]:
import pandas as pd
df2= pd.read_csv('sample_data/world_population.csv')
# In-Place Change: By default, set_index() will not modify the original DataFrame unless you specify the inplace=True parameter.

indexed_df= df2.set_index('Country')
# indexed_df.filter(items=['Continent','CCA3'], axis=1)
# indexed_df.filter(like='United',axis=0)
indexed_df.loc[indexed_df.index.str.contains("United", na=False)]
# df2.iloc[:, 3]

## **Sort Columns**

In [22]:
import pandas as pd
df= pd.read_csv('sample_data/world_population.csv')
required_colns = df.iloc[:,:4]

# required_colns[df['Rank']<10].sort_values(by=['Country'], ascending=False)    # Sorted Country in desc order
required_colns[df['Rank']<10].sort_values(by=['Rank', 'Country'], ascending=[False,True]) # Sorted Rank desc, country asc

Rank CCA3        Country           Capital
171     9  RUS         Russia            Moscow
16      8  BGD     Bangladesh             Dhaka
27      7  BRA         Brazil          Brasilia
149     6  NGA        Nigeria             Abuja
156     5  PAK       Pakistan         Islamabad
93      4  IDN      Indonesia           Jakarta
221     3  USA  United States  Washington, D.C.
92      2  IND          India         New Delhi
41      1  CHN          China           Beijing